# Generated by Django 4.0.4 on 2022-09-26 17:11

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=client.models.directory_path),
        ),
    ]
