# Generated by Django 4.0.4 on 2022-09-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_file_shared_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
