# Generated by Django 4.0.4 on 2022-09-27 16:50

import client.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_file_shared_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='file',
        ),
        migrations.CreateModel(
            name='FileFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=client.models.directory_path)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.folder')),
                ('shared_users', models.ManyToManyField(blank=True, null=True, related_name='allowed_file_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
