# Generated by Django 4.0.4 on 2022-09-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_folder_slug_alter_filefolder_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='filefolder',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
